### ISSUE TITLE
Entities are not sorted in Chrome

### ISSUE THREAD

**Issue by sarguido** [atecce/canon#2]
<img width="971" alt="screen shot 2019-03-01 at 4 28 19 pm" src="https://user-images.githubusercontent.com/3422080/53667462-0ec66500-3c3f-11e9-8973-5071efddc44e.png">

**Comment by atecce** [comment]
fixed by [55ee217c5d334a18a1ca96bd859a4e37a9f6abf5](https://github.com/atecce/www/commit/55ee217c5d334a18a1ca96bd859a4e37a9f6abf5)
