### ISSUE TITLE
Input is case sensitive

### ISSUE THREAD

**Issue by sarguido** [atecce/canon#3]
![case sensitivity](https://user-images.githubusercontent.com/3422080/53667755-e5f29f80-3c3f-11e9-9751-014e59cf23c5.gif)

**Comment by atecce** [comment]
should be fixed by https://github.com/atecce/canon/pull/5

<img width="383" alt="screen shot 2019-03-02 at 2 01 33 pm" src="https://user-images.githubusercontent.com/10567112/53686344-b2714d00-3cf3-11e9-9c5d-e7dad25fec41.png">
