### ISSUE TITLE
Fuzzy search is too fuzzy

### ISSUE THREAD

**Issue by sarguido** [atecce/canon#6]
![img_0002](https://user-images.githubusercontent.com/3422080/53688056-d93b7d80-3d0b-11e9-84a3-13a018ff6114.png)

**Comment by atecce** [comment]
i don't think i like [this](https://github.com/atecce/canon/pull/9)

<img width="1057" alt="screen shot 2019-03-02 at 7 00 06 pm" src="https://user-images.githubusercontent.com/10567112/53689188-eeb9a300-3d1d-11e9-8ab9-dc6736ea92ad.png">

**Comment by atecce** [comment]
[meh](https://github.com/atecce/canon/pull/9)
